Repository DecodersCommunity/WeatherApp, pull requests merged in 2023-10, with the labels that each got.

#3 made fully functional #1
  Docs/CONTRIBUTING.md
  Docs/LICENSE
  Images/clear.png
  Images/clouds.png
  Images/drizzle.png
  Images/humidity.png
  Images/mist.png
  Images/rain.png
  Images/search.png
  Images/snow.png
  Images/wind.png
  index.html
  script.js
  style.css
Labels: hactober, HACTOBERFEST-ACCEPTED, hacktoberfest, HACKTOBERFEST-ACCEPTED

#6 improved design and functionality
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#5 Update index.html
  WeatherApp/index.html
Labels: hacktoberfest-accepted
